export enum FACULTY_TH {
  "คณะมนุษยศาสตร์" = "01",
  "คณะศึกษาศาสตร์" = "02",
  "คณะวิจิตรศิลป์" = "03",
  "คณะสังคมศาสตร์" = "04",
  "คณะวิทยาศาสตร์" = "05",
  "คณะวิศวกรรมศาสตร์" = "06",
  "คณะแพทยศาสตร์" = "07",
  "คณะเกษตรศาสตร์" = "08",
  "คณะทันตแพทยศาสตร์" = "09",
  "คณะเภสัชศาสตร์" = "10",
  "คณะเทคนิคการแพทย์" = "11",
  "คณะพยาบาลศาสตร์" = "12",
  "คณะอุตสาหกรรมเกษตร" = "13",
  "คณะสัตวแพทยศาสตร์" = "14",
  "คณะบริหารธุรกิจ" = "15",
  "คณะเศรษฐศาสตร์" = "16",
  "คณะสถาปัตยกรรมศาสตร์" = "17",
  "คณะการสื่อสารมวลชน" = "18",
  "คณะรัฐศาสตร์และรัฐประศาสนศาสตร์" = "19",
  "คณะนิติศาสตร์" = "20",
  "วิทยาลัยศิลปะ สื่อ และเทคโนโลยี" = "21",
  "คณะสาธารณสุขศาสตร์" = "22",
  "วิทยาลัยการศึกษาและการจัดการทางทะเล" = "23",
  "วิทยาลัยนานาชาตินวัตกรรมดิจิทัล" = "24",
  "สถาบันนโยบายสาธารณะ" = "25",
  "สถาบันวิศวกรรมชีวการแพทย์" = "26",
  "สถาบันวิจัยวิทยาศาสตร์สุขภาพ" = "27",
}

export enum FACULTY_EN {
  "Faculty of Humanities" = "01",
  "Faculty of Education" = "02",
  "Faculty of Fine Arts" = "03",
  "Faculty of Social Sciences" = "04",
  "Faculty of Science" = "05",
  "Faculty of Engineering" = "06",
  "Faculty of Medicine" = "07",
  "Faculty of Agriculture" = "08",
  "Faculty of Dentistry" = "09",
  "Faculty of Pharmacy" = "10",
  "Faculty of Associated Medical Sciences" = "11",
  "Faculty of Nursing" = "12",
  "Faculty of Agro-Industry" = "13",
  "Faculty of Veterinary Medicine" = "14",
  "Faculty of Business Administration" = "15",
  "Faculty of Economics" = "16",
  "Faculty of Architecture" = "17",
  "Faculty of Mass Communication" = "18",
  "Faculty of Political Science and Public Administration" = "19",
  "Faculty of Law" = "20",
  "College of Arts= , Media and Technology" = "21",
  "Faculty of Public Health" = "22",
  "College of Education and Sea Management" = "23",
  "International College of Digital Innovation" = "24",
  "Chiang Mai University School of Public Policy" = "25",
  "Biomedical Engineering Institute" = "26",
  "Research Institute for Health Sciences" = "27",
}
